name: mansi_lathiya_portfolio
description: "Mansi Lathiya portfolio website"

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  animate_do: ^3.3.4
  shared_preferences: ^2.5.5
  visibility_detector: ^0.4.0+2
  font_awesome_flutter: ^11.0.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
